/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as ApiApkDecompileRouteImport } from './routes/api/apk/decompile'
import { Route as ApiApkRebuildRouteImport } from './routes/api/apk/rebuild'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkDecompileRoute = ApiApkDecompileRouteImport.update({
  id: '/api/apk/decompile',
  path: '/api/apk/decompile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApkRebuildRoute = ApiApkRebuildRouteImport.update({
  id: '/api/apk/rebuild',
  path: '/api/apk/rebuild',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/api/apk/decompile': typeof ApiApkDecompileRoute
  '/api/apk/rebuild': typeof ApiApkRebuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/api/apk/decompile': typeof ApiApkDecompileRoute
  '/api/apk/rebuild': typeof ApiApkRebuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/api/apk/decompile': typeof ApiApkDecompileRoute
  '/api/apk/rebuild': typeof ApiApkRebuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/api/apk/decompile' | '/api/apk/rebuild'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/api/apk/decompile' | '/api/apk/rebuild'
  id: '__root__' | '/' | '/editor' | '/api/apk/decompile' | '/api/apk/rebuild'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  ApiApkDecompileRoute: typeof ApiApkDecompileRoute
  ApiApkRebuildRoute: typeof ApiApkRebuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/decompile': {
      id: '/api/apk/decompile'
      path: '/api/apk/decompile'
      fullPath: '/api/apk/decompile'
      preLoaderRoute: typeof ApiApkDecompileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apk/rebuild': {
      id: '/api/apk/rebuild'
      path: '/api/apk/rebuild'
      fullPath: '/api/apk/rebuild'
      preLoaderRoute: typeof ApiApkRebuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  ApiApkDecompileRoute: ApiApkDecompileRoute,
  ApiApkRebuildRoute: ApiApkRebuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
